### ISSUE TITLE
smallrye-reactive-messaging - MQTT - Add metadata support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#10]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/466)
The MQTT connector should provide inbound and outbound metadata classes instead of a `MqttMessage`

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-reactive-messaging
upstream-issue: 466
upstream-status: closed
upstream-milestone: unplanned
```
