### ISSUE TITLE
smallrye-reactive-messaging - Customizing the underlying MQTT client 

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#11]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/693)
Hi,

a similar feature for the mqtt like: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/amqp/amqp.html#amqp-customization would be very helpful.

At the moment I need to convert a ca.crt to a java key store to use it for the mqtt connection.
But it would be nice to have the option to use it without converting it.

T

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-reactive-messaging
upstream-issue: 693
upstream-status: open
upstream-milestone: unplanned
```
