### ISSUE TITLE
smallrye-reactive-messaging - Document usages of Cloud Kafka Services

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#14]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/1695)
This epic is about adding detailed documentation about:

- [ ] Amazon MSK
- [ ]  Azure Service Hub
- [ ]  Red Hat OpenShift Streams with Apache Kafka
- [ ]  Confluent Cloud

The document should explain how to configure the Kafka connector to work with these providers.

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-reactive-messaging
upstream-issue: 1695
upstream-status: open
upstream-milestone: unplanned
```
