### ISSUE TITLE
smallrye-mutiny -  Reconsider and possibly remove the BOM

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#15]
(From https://github.com/smallrye/smallrye-mutiny/issues/943)
Is this something needed after all?

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-mutiny
upstream-issue: 943
upstream-status: open
upstream-milestone: 2.0.0 - https://github.com/smallrye/smallrye-mutiny/milestone/50
```
