### ISSUE TITLE
smallrye-mutiny - Add a 2.0 migration guide

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#16]
(From https://github.com/smallrye/smallrye-mutiny/issues/991)
Collect all important changes in 2.0 and explain how to migrate existing code bases.

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-mutiny
upstream-issue: 991
upstream-status: open
upstream-milestone: 2.0.0 - https://github.com/smallrye/smallrye-mutiny/milestone/50
```
