### ISSUE TITLE
smallrye-stork - ServiceDiscovery caching

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#17]
(From https://github.com/smallrye/smallrye-stork/issues/61)
Options:

- [ ] cache until failure - e.g. for Kubernetes PODs
- [X] refresh periodically
- [ ] server-side push

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 61
upstream-status: open
upstream-milestone: unplanned
```
