### ISSUE TITLE
smallrye-stork - Consider changing LoadBalancer to CDI bean instead of SPI

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#18]
(From https://github.com/smallrye/smallrye-stork/issues/64)
it's easier to test CDI beans than SPI providers. 
It could be nice to have both, a possibility to add LoadBalancers by creating CDI beans and by SPI

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 64
upstream-status: open
upstream-milestone: unplanned
```
