### ISSUE TITLE
smallrye-stork - External cache invalidation API

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#20]
(From https://github.com/smallrye/smallrye-stork/issues/299)
null

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 299
upstream-status: open
upstream-milestone: unplanned
```
