### ISSUE TITLE
smallrye-stork - Add a way to expose statistics to Metrics

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#21]
(From https://github.com/smallrye/smallrye-stork/issues/63)
Micrometer integration, probably through an abstraction layer, so that other metrics engines can be integrate too.

- service instances resolved
- service discovery executions
- load balancing selection metrics

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 63
upstream-status: open
upstream-milestone: unplanned
```
