### ISSUE TITLE
smallrye-mutiny - Move the website to MkDocs and adopt the Diátaxis Framework

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#7]
(From https://github.com/smallrye/smallrye-mutiny/issues/868)
See:

- https://squidfunk.github.io/mkdocs-material/
- https://diataxis.fr/

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-mutiny
upstream-issue: 868
upstream-status: open
upstream-milestone: 2.0.0 - https://github.com/smallrye/smallrye-mutiny/milestone/50
```
