### ISSUE TITLE
smallrye-mutiny - Migrate to Jakarta and MicroProfile Reactive Streams Operators 3.0

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-upstream-roadmap#8]
(From https://github.com/smallrye/smallrye-mutiny/issues/891)
Migrate to Jakarta namespace, especially update to MicroProfile Reactive Streams Operators 3.0.

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-mutiny
upstream-issue: 891
upstream-status: open
upstream-milestone: unplanned
```
